#!/bin/bash
#PSD3 Prototype for Internship Management System
#Version 1.0

function login() {

exit=0
quit=0

while [[ ! $exit -eq 1 ]];
do 

	#get username
	echo -n "Enter username: "
	read username
	#get password
	echo -n "Enter password: "
	read -s password
	
	#check credentials
	while read line           
	do           
		re="^([^,]+), (.*), (.*), (.*), (.*), (.*), (.*), (.*), (.*), (.*)$"
		[[ "$line" =~ $re ]] && Username="${BASH_REMATCH[1]}" && Password="${BASH_REMATCH[2]}" && Email="${BASH_REMATCH[3]}" && IsApproved="${BASH_REMATCH[4]}" && AccountType="${BASH_REMATCH[5]}" && FirstName="${BASH_REMATCH[6]}" && LastName="${BASH_REMATCH[7]}" && StudentType="${BASH_REMATCH[8]}" && StudentYear="${BASH_REMATCH[9]}" && OrganisationType="${BASH_REMATCH[10]}"
		if [ "$username" = "$Username" ]; then
			if [ "$password" = "$Password" ]; then
				exit=1
				echo -e "\nLogin Successful. Welcome $FirstName"
			else echo "Incorrent Password"
			fi
		fi
		if [ $exit -eq 1 ]; then break; fi
	done <.users.csv
	if [ "$AccountType" = "AccountType" ]; then
		echo "Nice Try you cheeky Bastard"
		exit=0
	fi
done

}


function menu() {
	echo -e "\nPlease choose an option from the menu below by entering the appropriate number and pressing enter. q to exit:"

	if [[ "$AccountType" = "student" ]]; then
		echo "1. Review advertisements"
		echo "2. Notify course coordinator of placement success"
		echo
		processMenuChoice
	elif [[ "$AccountType" = "coordinator" ]]; then
		echo "1. Review advertisements"
		echo "2. View current status of students’ internship applications"
		echo "3. Approve student internship placements"
		echo "4. Approve User"
		echo
		processMenuChoice
	elif [[ "$AccountType" = "academic" ]]; then
		echo "1. Submit advertisement"
		echo "2. View submitted advertisements"
		echo
		processMenuChoice
	elif [[ "$AccountType" = "organisation" ]]; then
		echo "1. Submit advertisement"
		echo "2. View submitted advertisements"
		echo
		processMenuChoice
	else quit=1
	fi
}

function processMenuChoice() {
	read choice #get user choice

	while [ -z "$choice" ]; #keep asking for choice if empty string entered
	do
		echo "No choice entered"
		echo -n "Enter choice and press enter: "
		read choice
	done

	if [[ "$choice" = "q" ]]; then
		quit=1
	elif [[ "$AccountType" = "student" && "$choice" -eq 1 ]]; then
		echo "ID, Owner, Duration, Payment, SECompliant, Positions, Info, Visible, Expires"
		cat .placement.csv | grep "true.*true"
		cat .placement.csv | grep "false.*true"
	elif [[ "$AccountType" = "student" && "$choice" -eq 2 ]]; then
		echo "choice 2" 
		processPlacement
	elif [[ "$AccountType" = "coordinator" && "$choice" -eq 1 ]]; then
		cat .placement.csv
	elif [[ "$AccountType" = "coordinator" && "$choice" -eq 2 ]]; then
		cat .studentPlacement
	elif [[ "$AccountType" = "coordinator" && "$choice" -eq 3 ]]; then
		echo "choice 3"
	elif [[ "$AccountType" = "coordinator" && "$choice" -eq 4 ]]; then
		echo "choice 4"
	elif [[ "$AccountType" = "academic" && "$choice" -eq 1 ]]; then
		echo "choice 1"
	elif [[ "$AccountType" = "academic" && "$choice" -eq 2 ]]; then
		echo "choice 2"
	elif [[ "$AccountType" = "organisation" && "$choice" -eq 1 ]]; then
		echo "choice 1"
	elif [[ "$AccountType" = "organisation" && "$choice" -eq 2 ]]; then
		echo "choice 2"	
	fi
	echo "Enter to continue"
	read cont

}

function processPlacement() {
	echo -e "\nPlease choose an option from the menu below by entering the appropriate number and pressing enter. q to exit:"

	echo "1. The placement was found using the University of Glasgow Internship Management System"
	echo "2. The placement was found externally"
	echo
	read choice #get user choice

	while [ -z "$choice" ]; #keep asking for choice if empty string entered
	do
		echo "No choice entered"
		echo -n "Enter choice and press enter: "
		read choice
	done

	if [[ "$choice" = "q" ]]; then
		cont=0
	elif [[ "$choice" -eq 1 ]]; then
	echo "Select the correct position by number"
		echo "ID, Owner, Duration, Payment, SECompliant, Positions, Info, Visible, Expires"
		cat .placement.csv | grep "true.*true"
		cat .placement.csv | grep "false.*true"
		read choice
		choice=$(cat .placement.csv | grep "$choice, ")
		echo $choice $username >> .studentPlacement
		echo "Thank you. Your response has been saved and is awaiting approval from the course coordinator. You will be contacted by email in due course."
		
		
	elif [[ "$choice" -eq 2 ]]; then
		echo "Enter Placement in form Owner, Duration, Payment, SECompliant, Positions, Info, Visible, Expires"
		read placement
		echo $placement $username >> .studentPlacement
		echo "Thank you. Your response has been saved and is awaiting approval from the course coordinator. You will be contacted by email in due course."
	fi
}



# START MAIN PROGRAM #
echo
echo "Welcome to the University of Glasgow Internship Management System"
echo
login
while [[ ! $quit -eq 1 ]];
do 
	menu
done

#result=$AccountType   # or result=`myfunc`
#echo $AccountType

